name: String-joiner benchmark

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install commons-lang3-3.13.0-SNAPSHOT
        run: mvn install:install-file -Dfile=string-builder/snapshot/commons-lang3-3.13.0-SNAPSHOT.jar -DpomFile=string-builder/snapshot/commons-lang3-3.13.0-SNAPSHOT.pom
      - name: mvn verify
        run: cd string-builder; mvn clean verify
      - name: run benchmark string-builder
        run: java -jar string-builder/target/benchmarks.jar

