name: String-joiner benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: mvn verify
        run: cd string-joiner; mvn clean verify
      - name: run benchmark
        run: java -jar string-joiner/target/benchmarks.jar

